"""empty message

Revision ID: 01c3dd947104
Revises: f9851831786c
Create Date: 2019-04-26 14:33:02.988563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c3dd947104'
down_revision = 'f9851831786c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('author', sa.String(length=15), nullable=False),
    sa.Column('desc', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('userid', sa.Integer(), nullable=False),
    sa.Column('bookid', sa.Integer(), nullable=False),
    sa.Column('numbers', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bookid'], ['book.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('userid', 'bookid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('book')
    # ### end Alembic commands ###
